### ISSUE TITLE
manual selection of photosynthesis boost doesn't have any effect

### ISSUE THREAD

**Issue by ProfessorSidon** [nerd-of-now/NCP-VGC-Damage-Calculator#10]
It seems that manually selecting a boost with photosynthesis doesn't have any effect

Without selection:
![image](https://user-images.githubusercontent.com/34562504/212559149-6ec51387-c230-438a-af39-67cea00629f3.png)

Selecting photosynthesis boost:
![image](https://user-images.githubusercontent.com/34562504/212559180-af18aaa5-d6ac-4f42-99c1-b7e624a2b7e7.png)

**Comment by nerd-of-now** [comment]
I might've done a poor job explaining it. The manual Protosynthesis boost is meant to just _choose_ which stat is boosted, not _give_ the actual boost itself. You still need sun to be active or for the Pokemon itself to hold Booster Energy in order to actually receive the boost. I could change this in an update though if it's too confusing.

**Comment by nerd-of-now** [comment]
This has now been changed to work in the way that you thought it worked beforehand. Sorry for any confusion!
7866332c1940ee1db20bc38ea05c60406007262c
