### ISSUE TITLE
Wigglytuff outdated data

### ISSUE THREAD

**Issue by Glazelf** [nerd-of-now/NCP-VGC-Damage-Calculator#11]
For Wigglytuff (and maybe some other Pokémon that changed typings/stats semi-recently) the typing and stats are not correct. The calculator defaults to pure Normal with 75 Sp.Atk, while this should be Normal/Fairy with 85 Sp.Atk.
I checked Azurill and even Jigglypuff, but it seems fine there. I tried to see if the typing.
![image](https://user-images.githubusercontent.com/35176230/213306597-64e69dc7-3fc7-4c5f-94c7-2d05724596c5.png)

This data should be assigned at https://github.com/nerd-of-now/NCP-VGC-Damage-Calculator/blob/main/script_res/pokedex.js#L9420 but doesn't seem like this is being displayed in the calculator, for Wigglytuff specifically at least.  
I had a look around but couldn't figure out why this is.

**Comment by nerd-of-now** [comment]
Found the issue. Wigglytuff is changed twice in var POKEDEX_XY, where the first one has the correct typing, stat change, and ability change, while the second only has the correct ability change. Since the second one is the latest change, it is the only one that occurs. Will update after I finish some other work in the calc.

**Comment by nerd-of-now** [comment]
178ad1486e0cf1abec07e7586198b03ee734cd98
