### ISSUE TITLE
Incorrect ADV mechanics

### ISSUE THREAD

**Issue by Akiak7** [nerd-of-now/NCP-VGC-Damage-Calculator#16]
Hi, I'd like to start using this for our Gen 3 VGC format (Orre Colosseum) but it seems that ADV mechanics are not correctly implemented. This can be seen by the fact that Earthquake deals more damage in single battles than in double battles, when it should deal the same amount of damage in Gen 3.

I don't know what other ADV mechanics are incorrect, but Showdown's calculator gets all the mechanics correctly, so I'm wondering if they could just be ported from there. The reason we don't want to use Showdown's calc is that it sets to level 100 by default.

**Comment by nerd-of-now** [comment]
Apologies for only seeing this now. Since this Damage Calc is forked from one of the earliest versions of Showdown's, none of its mechanics have been updated from said fork. Unfortunately, with the announcement of Regulation D and NAIC coming up, I need to focus on adding new sets to the Calc, so I may not be able to get to this until later in the month or even until July. As soon as Regulation D settles, I'll fix whatever is inaccurate, and for right now, I'll fix the spread damage in Doubles.

**Comment by nerd-of-now** [comment]
...Well that only took me too long. The mechanics actually weren't that far off but they are finally as accurate as I know them to be. https://github.com/nerd-of-now/NCP-VGC-Damage-Calculator/commit/c11cece85e1383fb71ffe6216db833386b93c8f9
